version: 2
build:
  os: ubuntu-20.04
  jobs:
    pre_install:
        # see https://github.com/readthedocs/readthedocs.org/issues/8201
      - git update-index --assume-unchanged docs/environment.yml docs/source/conf.py
      # install mesmer, needs to be editable
      - python -m pip install -e .
  tools:
    python: mambaforge-4.10
sphinx:
  configuration: docs/source/conf.py
conda:
  environment: docs/environment.yml
