version: 2
build:
  os: ubuntu-22.04
  jobs:
    post_checkout:
      # unshallow so the version works
      - git fetch --unshallow
    pre_install:
        # see https://github.com/readthedocs/readthedocs.org/issues/8201
      - git update-index --assume-unchanged docs/environment.yml docs/source/conf.py
      # install mesmer
      # * needs to be editable
      # * --no-deps to ensure minimal required deps
      - python -m pip install --no-deps -e .
  tools:
    python: mambaforge-22.9
sphinx:
  configuration: docs/source/conf.py
conda:
  environment: docs/environment.yml
