name: mesmer CI-CD
on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: py${{ matrix.python-version }}-${{ matrix.env }}
    runs-on: "ubuntu-latest"
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      fail-fast: false
      matrix:
        include:
          - env: "min-all-deps"
            python-version: "3.9"

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set environment variables
      run: |
        PY=${{ matrix.python-version }}
        # replace "." in matrix.python-version
        PY=${PY//./}
        echo "CONDA_ENV_FILE=ci/requirements/py${PY}-${{ matrix.env }}.yml" >> $GITHUB_ENV

    - name: Create conda environment
      uses: mamba-org/setup-micromamba@v1
      with:
        environment-name: mesmer-tests
        cache-downloads: true
        cache-downloads-key: "${{runner.os}}-${{runner.arch}}-py${{matrix.python-version}}"
        micromamba-version: 'latest'
        environment-file: ${{ env.CONDA_ENV_FILE }}
        create-args: >-
          python=${{ matrix.python-version }}

    - name: Install mesmer
      run: |
        python -m pip install --no-deps -e .

    - name: Conda info
      run: |
        conda info -a

    - name: Conda list
      run: conda list

    - name: Run tests
      run: python -u -m pytest
       -r a -v
       --all
       --cov=mesmer
       --cov-report=xml

    - name: Upload code coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
          file: ./coverage.xml
          flags: unittests
          env_vars: RUNNER_OS,PYTHON_VERSION
          name: codecov-umbrella
          fail_ci_if_error: false
